### PR TITLE
Intial version of StringDB REST service to serve up STRING DB

### PR DESCRIPTION
**Pull request by darth-pr**
- Known and Predicted Protein-Protein Interactions

Sample call 
PUT
Aatf
http://localhost:8080/shangridocs-services/services/stringdb/query

Sample response:

[{"link":"http://string-db.org/newstring_cgi/show_network_section.pl?identifier=10116.ENSRNOP00000000258","title":"Aatf","description":"Protein AATF ; May function as a general inhibitor of the histone deacetylase HDAC1. Binding to the pocket region of RB1 may displace HDAC1 from RB1/E2F complexes, leading to activation of E2F target genes and cell cycle progression. Conversely, displacement of HDAC1 from SP1 bound to the CDKN1A promoter leads to increased expression of this CDK inhibitor and blocks cell cycle progression. May negatively regulate the pro-apoptotic activity of DAPK3/ZIPK. Can act cooperatively with TSG101 to stimulate AR mediated transcription activation (By similarity). May negatively regulate the pro- [...] ","taxonName":"Rattus norvegicus","ncbiTaxonId":10116}, ...]

### CODE REVIEW

**Comment by chrismattmann** [comment]
@darth-pr there are conflicts in this can you resolve?

**Comment by darth-pr** [comment]
Done

**Comment by chrismattmann** [comment]
merged! thanks @darth-pr

**Comment by chrismattmann** [comment]
@darth-pr can you add an example call to the README.md?

**Comment by darth-pr** [comment]
Sure no problem.

**Pull request merged**
